//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLARAC()
        {
            this.TBLKIRA = new HashSet<TBLKIRA>();
        }
    
        public int AraçID { get; set; }
        public Nullable<int> MarkaID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Renk { get; set; }
        public string MotorHacmi { get; set; }
        public string Kilometresi { get; set; }
        public string Resim { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Yıl { get; set; }
    
        public virtual TBLMARKA TBLMARKA { get; set; }
        public virtual TBLMODEL TBLMODEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKIRA> TBLKIRA { get; set; }
    }
}
