//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFirmaUrun
    {
        public int FirmaUrunID { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public string UrunAd { get; set; }
        public string Miktar { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<System.DateTime> AlinmaTarihi { get; set; }
    
        public virtual TBLFİRMA TBLFİRMA { get; set; }
    }
}
