//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGIRIS
    {
        public int girisid { get; set; }
        public string usr { get; set; }
        public string pwd { get; set; }
    }
}
