//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGELİR
    {
        public int GelirID { get; set; }
        public string İslem { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Adı { get; set; }
        public Nullable<decimal> Tutar { get; set; }
    }
}
