//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHATIRLATMA
    {
        public int HatırlatmaID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Acıklama { get; set; }
        public Nullable<System.DateTime> EklemeTarihi { get; set; }
        public Nullable<bool> Durumu { get; set; }
    }
}
