//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKIRA
    {
        public int kiraid { get; set; }
        public Nullable<int> musteriid { get; set; }
        public Nullable<int> markaid { get; set; }
        public Nullable<int> modelid { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public Nullable<int> aracid { get; set; }
    
        public virtual TBLARAC TBLARAC { get; set; }
        public virtual TBLMARKA TBLMARKA { get; set; }
        public virtual TBLMODEL TBLMODEL { get; set; }
        public virtual TBLMUSTERİ TBLMUSTERİ { get; set; }
    }
}
