//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKİRA
    {
        public int KiraID { get; set; }
        public Nullable<int> RezervasyonID { get; set; }
        public string KiralamaSuresi { get; set; }
        public Nullable<decimal> Ücreti { get; set; }
    
        public virtual TBLREZERVASYON TBLREZERVASYON { get; set; }
    }
}
