//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMUSTERİ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERİ()
        {
            this.TBLKIRA = new HashSet<TBLKIRA>();
        }
    
        public int MusteriID { get; set; }
        public string TcKimlik { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Cinsiyeti { get; set; }
        public Nullable<System.DateTime> DoğumTarihi { get; set; }
        public string Email { get; set; }
        public string CepTel { get; set; }
        public string Adres { get; set; }
        public string MüşteriResim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKIRA> TBLKIRA { get; set; }
    }
}
