//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSODEME
    {
        public int OdemeID { get; set; }
        public string OdemeTuru { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public Nullable<decimal> Odenen { get; set; }
        public Nullable<int> PersID { get; set; }
    
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
    }
}
