//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPERSONEL()
        {
            this.TBLPERSODEME = new HashSet<TBLPERSODEME>();
        }
    
        public int PersID { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public Nullable<System.DateTime> BaşlangıçTarihi { get; set; }
        public string Görevi { get; set; }
        public Nullable<decimal> Maaş { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Notu { get; set; }
        public string Resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLPERSODEME> TBLPERSODEME { get; set; }
    }
}
