//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSATISLAR
    {
        public int SeansID { get; set; }
        public Nullable<int> KoltukNo { get; set; }
        public Nullable<int> Seans { get; set; }
        public Nullable<System.DateTime> SatisTarihi { get; set; }
        public string Isim { get; set; }
        public Nullable<decimal> Ucret { get; set; }
    }
}
