//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLURUN
    {
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public string MARKASI { get; set; }
        public Nullable<decimal> ALISFIYATI { get; set; }
        public Nullable<decimal> SATISFIYATI { get; set; }
        public Nullable<short> STOKADET { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    
        public virtual TBLFIRMAODEME TBLFIRMAODEME { get; set; }
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
    }
}
