//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoKiralamav2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLÇEKSENET
    {
        public int çeksenetID { get; set; }
        public string Türü { get; set; }
        public Nullable<System.DateTime> Tarihi { get; set; }
        public string Firma { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public string Acıklama { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
